name: smart_permission_flow_example
description: Demonstrates the smart_permission_flow package.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  smart_permission_flow:
    path: ..

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
